<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-2IFVM62" failures="2" tests="2" name="Test(failed)" time="16.689" errors="0" timestamp="2022-08-05T15:01:06 PDT">
  <testcase classname="com.obsqura.scripts.TestClass" name="invalidLogin4" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void com.obsqura.scripts.TestClass.invalidLogin4(java.lang.String) throws java.io.IOException requires a @DataProvider named : dataProvider1">
      <![CDATA[org.testng.TestNGException: 
Method public void com.obsqura.scripts.TestClass.invalidLogin4(java.lang.String) throws java.io.IOException requires a @DataProvider named : dataProvider1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin4 -->
  <testcase classname="com.obsqura.scripts.TestClass" name="invalidLogin2" time="2.42">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Password is required] but found [Epic sadface: Password is required1]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Password is required] but found [Epic sadface: Password is required1]
at com.obsqura.scripts.TestClass.invalidLogin2(TestClass.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin2 -->
  <testcase classname="com.obsqura.scripts.TestClass" name="invalidLogin5" time="0.0">
    <ignored/>
  </testcase> <!-- invalidLogin5 -->
  <testcase classname="com.obsqura.scripts.TestClass" name="verifyLogin" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLogin -->
  <testcase classname="com.obsqura.scripts.TestClass" name="invalidLogin1" time="0.0">
    <ignored/>
  </testcase> <!-- invalidLogin1 -->
</testsuite> <!-- Test(failed) -->
